CREATE OR REPLACE TABLE raw_outage_snapshots AS
SELECT
    CAST(outage_id AS VARCHAR) AS outage_id,
    CAST(customers_affected AS INTEGER) AS customers_affected,

    -- Hydro start/restore timestamps in legacy CSVs are Quebec wall-clock
    -- values. New snapshots can already carry an explicit UTC offset.
    CASE
        WHEN start_time IS NULL THEN NULL
        WHEN regexp_matches(CAST(start_time AS VARCHAR), '(Z|[+-][0-9]{2}:?[0-9]{2})$')
            THEN TRY_CAST(start_time AS TIMESTAMPTZ)
        ELSE timezone('America/Toronto', TRY_CAST(start_time AS TIMESTAMP))
    END AS start_time,

    CASE
        WHEN estimated_restore IS NULL THEN NULL
        WHEN regexp_matches(CAST(estimated_restore AS VARCHAR), '(Z|[+-][0-9]{2}:?[0-9]{2})$')
            THEN TRY_CAST(estimated_restore AS TIMESTAMPTZ)
        ELSE timezone('America/Toronto', TRY_CAST(estimated_restore AS TIMESTAMP))
    END AS estimated_restore,

    CAST(status_code AS VARCHAR) AS status_code,
    CAST(status AS VARCHAR) AS status,
    TRY_CAST(cause_code AS DOUBLE) AS cause_code,
    CAST(cause_label AS VARCHAR) AS cause_label,
    CAST(municipality_id AS INTEGER) AS municipality_id,

    -- Captures generated by this project have always represented UTC.
    CASE
        WHEN captured_at IS NULL THEN NULL
        WHEN regexp_matches(CAST(captured_at AS VARCHAR), '(Z|[+-][0-9]{2}:?[0-9]{2})$')
            THEN TRY_CAST(captured_at AS TIMESTAMPTZ)
        ELSE timezone('UTC', TRY_CAST(captured_at AS TIMESTAMP))
    END AS captured_at,

    CAST(lon AS DOUBLE) AS lon,
    CAST(lat AS DOUBLE) AS lat
FROM read_csv_auto('data/raw/hydroquebec_history.csv', header = true);
