from __future__ import annotations

from typing import Any

import pandas as pd

UTC_TIMEZONE = "UTC"
QUEBEC_TIMEZONE = "America/Toronto"


def normalize_timestamp(value: Any, *, naive_timezone: str) -> pd.Timestamp | pd.NaT:
    """Return an aware UTC timestamp.

    Hydro outage ``start_time`` and ``estimated_restore`` values are Quebec
    wall-clock times when no offset is present. Capture timestamps generated by
    this project are UTC wall-clock times when no offset is present. Newer
    snapshots may already contain an explicit offset; those values are simply
    converted to UTC.
    """
    if value is None:
        return pd.NaT

    try:
        if pd.isna(value):
            return pd.NaT
    except (TypeError, ValueError):
        pass

    try:
        timestamp = pd.Timestamp(value)
    except (TypeError, ValueError):
        return pd.NaT

    if pd.isna(timestamp):
        return pd.NaT

    if timestamp.tzinfo is None:
        try:
            timestamp = timestamp.tz_localize(
                naive_timezone,
                ambiguous=False,
                nonexistent="shift_forward",
            )
        except (TypeError, ValueError, OverflowError):
            return pd.NaT

    return timestamp.tz_convert(UTC_TIMEZONE)


def normalize_timestamp_series(
    series: pd.Series,
    *,
    naive_timezone: str,
) -> pd.Series:
    """Normalize a pandas Series to ``datetime64[ns, UTC]`` safely."""
    normalized = series.map(
        lambda value: normalize_timestamp(value, naive_timezone=naive_timezone)
    )
    return pd.to_datetime(normalized, errors="coerce", utc=True)


def normalize_capture_series(series: pd.Series) -> pd.Series:
    """Normalize capture timestamps, interpreting legacy naive values as UTC."""
    return normalize_timestamp_series(series, naive_timezone=UTC_TIMEZONE)


def normalize_hydro_local_series(series: pd.Series) -> pd.Series:
    """Normalize Hydro wall-clock timestamps, interpreting naive values in Quebec."""
    return normalize_timestamp_series(series, naive_timezone=QUEBEC_TIMEZONE)
